// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/ServiceWeaver/weaver/Main",
		Iface:     reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(app{}),
		Listeners: []string{"lis"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦58ef135f:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→raycat/subFileSourceProvider⟧\n⟦06ebe5e4:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→raycat/subURLSourceProvider⟧\n⟦d535aefb:wEaVeRlIsTeNeRs:github.com/ServiceWeaver/weaver/Main→lis⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "raycat/subFileSourceProvider",
		Iface: reflect.TypeOf((*subFileSourceProvider)(nil)).Elem(),
		Impl:  reflect.TypeOf(subFileSource{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return subFileSourceProvider_local_stub{impl: impl.(subFileSourceProvider), tracer: tracer, updateFileSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subFileSourceProvider", Method: "UpdateFileSub", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return subFileSourceProvider_client_stub{stub: stub, updateFileSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subFileSourceProvider", Method: "UpdateFileSub", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return subFileSourceProvider_server_stub{impl: impl.(subFileSourceProvider), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return subFileSourceProvider_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "raycat/subURLSourceProvider",
		Iface: reflect.TypeOf((*subURLSourceProvider)(nil)).Elem(),
		Impl:  reflect.TypeOf(subURLSource{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return subURLSourceProvider_local_stub{impl: impl.(subURLSourceProvider), tracer: tracer, updateUrlSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subURLSourceProvider", Method: "UpdateUrlSub", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return subURLSourceProvider_client_stub{stub: stub, updateUrlSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subURLSourceProvider", Method: "UpdateUrlSub", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return subURLSourceProvider_server_stub{impl: impl.(subURLSourceProvider), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return subURLSourceProvider_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[weaver.Main] = (*app)(nil)
var _ weaver.InstanceOf[subFileSourceProvider] = (*subFileSource)(nil)
var _ weaver.InstanceOf[subURLSourceProvider] = (*subURLSource)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*app)(nil)
var _ weaver.Unrouted = (*subFileSource)(nil)
var _ weaver.Unrouted = (*subURLSource)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

type subFileSourceProvider_local_stub struct {
	impl                 subFileSourceProvider
	tracer               trace.Tracer
	updateFileSubMetrics *codegen.MethodMetrics
}

// Check that subFileSourceProvider_local_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_local_stub)(nil)

func (s subFileSourceProvider_local_stub) UpdateFileSub(ctx context.Context) (r0 []byte, err error) {
	// Update metrics.
	begin := s.updateFileSubMetrics.Begin()
	defer func() { s.updateFileSubMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subFileSourceProvider.UpdateFileSub", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateFileSub(ctx)
}

type subURLSourceProvider_local_stub struct {
	impl                subURLSourceProvider
	tracer              trace.Tracer
	updateUrlSubMetrics *codegen.MethodMetrics
}

// Check that subURLSourceProvider_local_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_local_stub)(nil)

func (s subURLSourceProvider_local_stub) UpdateUrlSub(ctx context.Context) (r0 []byte, err error) {
	// Update metrics.
	begin := s.updateUrlSubMetrics.Begin()
	defer func() { s.updateUrlSubMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subURLSourceProvider.UpdateUrlSub", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateUrlSub(ctx)
}

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

type subFileSourceProvider_client_stub struct {
	stub                 codegen.Stub
	updateFileSubMetrics *codegen.MethodMetrics
}

// Check that subFileSourceProvider_client_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_client_stub)(nil)

func (s subFileSourceProvider_client_stub) UpdateFileSub(ctx context.Context) (r0 []byte, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateFileSubMetrics.Begin()
	defer func() { s.updateFileSubMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subFileSourceProvider.UpdateFileSub", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_byte_87461245(dec)
	err = dec.Error()
	return
}

type subURLSourceProvider_client_stub struct {
	stub                codegen.Stub
	updateUrlSubMetrics *codegen.MethodMetrics
}

// Check that subURLSourceProvider_client_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_client_stub)(nil)

func (s subURLSourceProvider_client_stub) UpdateUrlSub(ctx context.Context) (r0 []byte, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateUrlSubMetrics.Begin()
	defer func() { s.updateUrlSubMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subURLSourceProvider.UpdateUrlSub", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_byte_87461245(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.5 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

type subFileSourceProvider_server_stub struct {
	impl    subFileSourceProvider
	addLoad func(key uint64, load float64)
}

// Check that subFileSourceProvider_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*subFileSourceProvider_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s subFileSourceProvider_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "UpdateFileSub":
		return s.updateFileSub
	default:
		return nil
	}
}

func (s subFileSourceProvider_server_stub) updateFileSub(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateFileSub(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_byte_87461245(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type subURLSourceProvider_server_stub struct {
	impl    subURLSourceProvider
	addLoad func(key uint64, load float64)
}

// Check that subURLSourceProvider_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*subURLSourceProvider_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s subURLSourceProvider_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "UpdateUrlSub":
		return s.updateUrlSub
	default:
		return nil
	}
}

func (s subURLSourceProvider_server_stub) updateUrlSub(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateUrlSub(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_byte_87461245(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

type subFileSourceProvider_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that subFileSourceProvider_reflect_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_reflect_stub)(nil)

func (s subFileSourceProvider_reflect_stub) UpdateFileSub(ctx context.Context) (r0 []byte, err error) {
	err = s.caller("UpdateFileSub", ctx, []any{}, []any{&r0})
	return
}

type subURLSourceProvider_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that subURLSourceProvider_reflect_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_reflect_stub)(nil)

func (s subURLSourceProvider_reflect_stub) UpdateUrlSub(ctx context.Context) (r0 []byte, err error) {
	err = s.caller("UpdateUrlSub", ctx, []any{}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*subFileSourceConfig)(nil)

type __is_subFileSourceConfig[T ~struct {
	weaver.AutoMarshal
	FilePaths []string "toml:\"file_paths\""
}] struct{}

var _ __is_subFileSourceConfig[subFileSourceConfig]

func (x *subFileSourceConfig) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("subFileSourceConfig.WeaverMarshal: nil receiver"))
	}
	serviceweaver_enc_slice_string_4af10117(enc, x.FilePaths)
}

func (x *subFileSourceConfig) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("subFileSourceConfig.WeaverUnmarshal: nil receiver"))
	}
	x.FilePaths = serviceweaver_dec_slice_string_4af10117(dec)
}

func serviceweaver_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func serviceweaver_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

var _ codegen.AutoMarshal = (*subUrlSourceConfig)(nil)

type __is_subUrlSourceConfig[T ~struct {
	weaver.AutoMarshal
	TimeoutSeconds int      "toml:\"timeout_seconds\""
	UrlSubs        []string "toml:\"url_subs\""
}] struct{}

var _ __is_subUrlSourceConfig[subUrlSourceConfig]

func (x *subUrlSourceConfig) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("subUrlSourceConfig.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.TimeoutSeconds)
	serviceweaver_enc_slice_string_4af10117(enc, x.UrlSubs)
}

func (x *subUrlSourceConfig) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("subUrlSourceConfig.WeaverUnmarshal: nil receiver"))
	}
	x.TimeoutSeconds = dec.Int()
	x.UrlSubs = serviceweaver_dec_slice_string_4af10117(dec)
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_byte_87461245(enc *codegen.Encoder, arg []byte) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.Byte(arg[i])
	}
}

func serviceweaver_dec_slice_byte_87461245(dec *codegen.Decoder) []byte {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]byte, n)
	for i := 0; i < n; i++ {
		res[i] = dec.Byte()
	}
	return res
}
