// Code generated by "weaver generate". DO NOT EDIT.
//go:build !ignoreWeaverGen

package main

import (
	"context"
	"errors"
	"fmt"
	"github.com/ServiceWeaver/weaver"
	"github.com/ServiceWeaver/weaver/runtime/codegen"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"
	"reflect"
)

func init() {
	codegen.Register(codegen.Registration{
		Name:      "github.com/ServiceWeaver/weaver/Main",
		Iface:     reflect.TypeOf((*weaver.Main)(nil)).Elem(),
		Impl:      reflect.TypeOf(app{}),
		Listeners: []string{"lis"},
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return main_local_stub{impl: impl.(weaver.Main), tracer: tracer}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any { return main_client_stub{stub: stub} },
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return main_server_stub{impl: impl.(weaver.Main), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return main_reflect_stub{caller: caller}
		},
		RefData: "⟦24d0e964:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→raycat/subConfigureProvider⟧\n⟦58ef135f:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→raycat/subFileSourceProvider⟧\n⟦06ebe5e4:wEaVeReDgE:github.com/ServiceWeaver/weaver/Main→raycat/subURLSourceProvider⟧\n⟦d535aefb:wEaVeRlIsTeNeRs:github.com/ServiceWeaver/weaver/Main→lis⟧\n",
	})
	codegen.Register(codegen.Registration{
		Name:  "raycat/subConfigureProvider",
		Iface: reflect.TypeOf((*subConfigureProvider)(nil)).Elem(),
		Impl:  reflect.TypeOf(subConfigure{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return subConfigureProvider_local_stub{impl: impl.(subConfigureProvider), tracer: tracer, getResponseOptionMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetResponseOption", Remote: false, Generated: true}), getSubAuthParamNameMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubAuthParamName", Remote: false, Generated: true}), getSubFilePathsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubFilePaths", Remote: false, Generated: true}), getSubPublishPathMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubPublishPath", Remote: false, Generated: true}), getUrlSubsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetUrlSubs", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return subConfigureProvider_client_stub{stub: stub, getResponseOptionMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetResponseOption", Remote: true, Generated: true}), getSubAuthParamNameMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubAuthParamName", Remote: true, Generated: true}), getSubFilePathsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubFilePaths", Remote: true, Generated: true}), getSubPublishPathMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetSubPublishPath", Remote: true, Generated: true}), getUrlSubsMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subConfigureProvider", Method: "GetUrlSubs", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return subConfigureProvider_server_stub{impl: impl.(subConfigureProvider), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return subConfigureProvider_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "raycat/subFileSourceProvider",
		Iface: reflect.TypeOf((*subFileSourceProvider)(nil)).Elem(),
		Impl:  reflect.TypeOf(subFileSource{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return subFileSourceProvider_local_stub{impl: impl.(subFileSourceProvider), tracer: tracer, updateFileSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subFileSourceProvider", Method: "UpdateFileSub", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return subFileSourceProvider_client_stub{stub: stub, updateFileSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subFileSourceProvider", Method: "UpdateFileSub", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return subFileSourceProvider_server_stub{impl: impl.(subFileSourceProvider), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return subFileSourceProvider_reflect_stub{caller: caller}
		},
		RefData: "",
	})
	codegen.Register(codegen.Registration{
		Name:  "raycat/subURLSourceProvider",
		Iface: reflect.TypeOf((*subURLSourceProvider)(nil)).Elem(),
		Impl:  reflect.TypeOf(subURLSource{}),
		LocalStubFn: func(impl any, caller string, tracer trace.Tracer) any {
			return subURLSourceProvider_local_stub{impl: impl.(subURLSourceProvider), tracer: tracer, updateUrlSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subURLSourceProvider", Method: "UpdateUrlSub", Remote: false, Generated: true})}
		},
		ClientStubFn: func(stub codegen.Stub, caller string) any {
			return subURLSourceProvider_client_stub{stub: stub, updateUrlSubMetrics: codegen.MethodMetricsFor(codegen.MethodLabels{Caller: caller, Component: "raycat/subURLSourceProvider", Method: "UpdateUrlSub", Remote: true, Generated: true})}
		},
		ServerStubFn: func(impl any, addLoad func(uint64, float64)) codegen.Server {
			return subURLSourceProvider_server_stub{impl: impl.(subURLSourceProvider), addLoad: addLoad}
		},
		ReflectStubFn: func(caller func(string, context.Context, []any, []any) error) any {
			return subURLSourceProvider_reflect_stub{caller: caller}
		},
		RefData: "",
	})
}

// weaver.InstanceOf checks.
var _ weaver.InstanceOf[weaver.Main] = (*app)(nil)
var _ weaver.InstanceOf[subConfigureProvider] = (*subConfigure)(nil)
var _ weaver.InstanceOf[subFileSourceProvider] = (*subFileSource)(nil)
var _ weaver.InstanceOf[subURLSourceProvider] = (*subURLSource)(nil)

// weaver.Router checks.
var _ weaver.Unrouted = (*app)(nil)
var _ weaver.Unrouted = (*subConfigure)(nil)
var _ weaver.Unrouted = (*subFileSource)(nil)
var _ weaver.Unrouted = (*subURLSource)(nil)

// Local stub implementations.

type main_local_stub struct {
	impl   weaver.Main
	tracer trace.Tracer
}

// Check that main_local_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_local_stub)(nil)

type subConfigureProvider_local_stub struct {
	impl                       subConfigureProvider
	tracer                     trace.Tracer
	getResponseOptionMetrics   *codegen.MethodMetrics
	getSubAuthParamNameMetrics *codegen.MethodMetrics
	getSubFilePathsMetrics     *codegen.MethodMetrics
	getSubPublishPathMetrics   *codegen.MethodMetrics
	getUrlSubsMetrics          *codegen.MethodMetrics
}

// Check that subConfigureProvider_local_stub implements the subConfigureProvider interface.
var _ subConfigureProvider = (*subConfigureProvider_local_stub)(nil)

func (s subConfigureProvider_local_stub) GetResponseOption(ctx context.Context) (r0 *responseOption, err error) {
	// Update metrics.
	begin := s.getResponseOptionMetrics.Begin()
	defer func() { s.getResponseOptionMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subConfigureProvider.GetResponseOption", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetResponseOption(ctx)
}

func (s subConfigureProvider_local_stub) GetSubAuthParamName(ctx context.Context) (r0 string, err error) {
	// Update metrics.
	begin := s.getSubAuthParamNameMetrics.Begin()
	defer func() { s.getSubAuthParamNameMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subConfigureProvider.GetSubAuthParamName", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetSubAuthParamName(ctx)
}

func (s subConfigureProvider_local_stub) GetSubFilePaths(ctx context.Context, a0 string) (r0 []string, err error) {
	// Update metrics.
	begin := s.getSubFilePathsMetrics.Begin()
	defer func() { s.getSubFilePathsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subConfigureProvider.GetSubFilePaths", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetSubFilePaths(ctx, a0)
}

func (s subConfigureProvider_local_stub) GetSubPublishPath(ctx context.Context) (r0 string, err error) {
	// Update metrics.
	begin := s.getSubPublishPathMetrics.Begin()
	defer func() { s.getSubPublishPathMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subConfigureProvider.GetSubPublishPath", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetSubPublishPath(ctx)
}

func (s subConfigureProvider_local_stub) GetUrlSubs(ctx context.Context, a0 string) (r0 []string, r1 int, err error) {
	// Update metrics.
	begin := s.getUrlSubsMetrics.Begin()
	defer func() { s.getUrlSubsMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subConfigureProvider.GetUrlSubs", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.GetUrlSubs(ctx, a0)
}

type subFileSourceProvider_local_stub struct {
	impl                 subFileSourceProvider
	tracer               trace.Tracer
	updateFileSubMetrics *codegen.MethodMetrics
}

// Check that subFileSourceProvider_local_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_local_stub)(nil)

func (s subFileSourceProvider_local_stub) UpdateFileSub(ctx context.Context, a0 []string) (r0 []byte, err error) {
	// Update metrics.
	begin := s.updateFileSubMetrics.Begin()
	defer func() { s.updateFileSubMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subFileSourceProvider.UpdateFileSub", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateFileSub(ctx, a0)
}

type subURLSourceProvider_local_stub struct {
	impl                subURLSourceProvider
	tracer              trace.Tracer
	updateUrlSubMetrics *codegen.MethodMetrics
}

// Check that subURLSourceProvider_local_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_local_stub)(nil)

func (s subURLSourceProvider_local_stub) UpdateUrlSub(ctx context.Context, a0 []string, a1 int) (r0 []byte, err error) {
	// Update metrics.
	begin := s.updateUrlSubMetrics.Begin()
	defer func() { s.updateUrlSubMetrics.End(begin, err != nil, 0, 0) }()
	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.tracer.Start(ctx, "main.subURLSourceProvider.UpdateUrlSub", trace.WithSpanKind(trace.SpanKindInternal))
		defer func() {
			if err != nil {
				span.RecordError(err)
				span.SetStatus(codes.Error, err.Error())
			}
			span.End()
		}()
	}

	return s.impl.UpdateUrlSub(ctx, a0, a1)
}

// Client stub implementations.

type main_client_stub struct {
	stub codegen.Stub
}

// Check that main_client_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_client_stub)(nil)

type subConfigureProvider_client_stub struct {
	stub                       codegen.Stub
	getResponseOptionMetrics   *codegen.MethodMetrics
	getSubAuthParamNameMetrics *codegen.MethodMetrics
	getSubFilePathsMetrics     *codegen.MethodMetrics
	getSubPublishPathMetrics   *codegen.MethodMetrics
	getUrlSubsMetrics          *codegen.MethodMetrics
}

// Check that subConfigureProvider_client_stub implements the subConfigureProvider interface.
var _ subConfigureProvider = (*subConfigureProvider_client_stub)(nil)

func (s subConfigureProvider_client_stub) GetResponseOption(ctx context.Context) (r0 *responseOption, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getResponseOptionMetrics.Begin()
	defer func() { s.getResponseOptionMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subConfigureProvider.GetResponseOption", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 0, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_ptr_responseOption_4a459b91(dec)
	err = dec.Error()
	return
}

func (s subConfigureProvider_client_stub) GetSubAuthParamName(ctx context.Context) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getSubAuthParamNameMetrics.Begin()
	defer func() { s.getSubAuthParamNameMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subConfigureProvider.GetSubAuthParamName", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 1, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

func (s subConfigureProvider_client_stub) GetSubFilePaths(ctx context.Context, a0 string) (r0 []string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getSubFilePathsMetrics.Begin()
	defer func() { s.getSubFilePathsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subConfigureProvider.GetSubFilePaths", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 2, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_string_4af10117(dec)
	err = dec.Error()
	return
}

func (s subConfigureProvider_client_stub) GetSubPublishPath(ctx context.Context) (r0 string, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getSubPublishPathMetrics.Begin()
	defer func() { s.getSubPublishPathMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subConfigureProvider.GetSubPublishPath", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	var shardKey uint64

	// Call the remote method.
	var results []byte
	results, err = s.stub.Run(ctx, 3, nil, shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = dec.String()
	err = dec.Error()
	return
}

func (s subConfigureProvider_client_stub) GetUrlSubs(ctx context.Context, a0 string) (r0 []string, r1 int, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.getUrlSubsMetrics.Begin()
	defer func() { s.getUrlSubsMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subConfigureProvider.GetUrlSubs", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Preallocate a buffer of the right size.
	size := 0
	size += (4 + len(a0))
	enc := codegen.NewEncoder()
	enc.Reset(size)

	// Encode arguments.
	enc.String(a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 4, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_string_4af10117(dec)
	r1 = dec.Int()
	err = dec.Error()
	return
}

type subFileSourceProvider_client_stub struct {
	stub                 codegen.Stub
	updateFileSubMetrics *codegen.MethodMetrics
}

// Check that subFileSourceProvider_client_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_client_stub)(nil)

func (s subFileSourceProvider_client_stub) UpdateFileSub(ctx context.Context, a0 []string) (r0 []byte, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateFileSubMetrics.Begin()
	defer func() { s.updateFileSubMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subFileSourceProvider.UpdateFileSub", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_string_4af10117(enc, a0)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_byte_87461245(dec)
	err = dec.Error()
	return
}

type subURLSourceProvider_client_stub struct {
	stub                codegen.Stub
	updateUrlSubMetrics *codegen.MethodMetrics
}

// Check that subURLSourceProvider_client_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_client_stub)(nil)

func (s subURLSourceProvider_client_stub) UpdateUrlSub(ctx context.Context, a0 []string, a1 int) (r0 []byte, err error) {
	// Update metrics.
	var requestBytes, replyBytes int
	begin := s.updateUrlSubMetrics.Begin()
	defer func() { s.updateUrlSubMetrics.End(begin, err != nil, requestBytes, replyBytes) }()

	span := trace.SpanFromContext(ctx)
	if span.SpanContext().IsValid() {
		// Create a child span for this method.
		ctx, span = s.stub.Tracer().Start(ctx, "main.subURLSourceProvider.UpdateUrlSub", trace.WithSpanKind(trace.SpanKindClient))
	}

	defer func() {
		// Catch and return any panics detected during encoding/decoding/rpc.
		if err == nil {
			err = codegen.CatchPanics(recover())
			if err != nil {
				err = errors.Join(weaver.RemoteCallError, err)
			}
		}

		if err != nil {
			span.RecordError(err)
			span.SetStatus(codes.Error, err.Error())
		}
		span.End()

	}()

	// Encode arguments.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_string_4af10117(enc, a0)
	enc.Int(a1)
	var shardKey uint64

	// Call the remote method.
	requestBytes = len(enc.Data())
	var results []byte
	results, err = s.stub.Run(ctx, 0, enc.Data(), shardKey)
	replyBytes = len(results)
	if err != nil {
		err = errors.Join(weaver.RemoteCallError, err)
		return
	}

	// Decode the results.
	dec := codegen.NewDecoder(results)
	r0 = serviceweaver_dec_slice_byte_87461245(dec)
	err = dec.Error()
	return
}

// Note that "weaver generate" will always generate the error message below.
// Everything is okay. The error message is only relevant if you see it when
// you run "go build" or "go run".
var _ codegen.LatestVersion = codegen.Version[[0][24]struct{}](`

ERROR: You generated this file with 'weaver generate' v0.24.5 (codegen
version v0.24.0). The generated code is incompatible with the version of the
github.com/ServiceWeaver/weaver module that you're using. The weaver module
version can be found in your go.mod file or by running the following command.

    go list -m github.com/ServiceWeaver/weaver

We recommend updating the weaver module and the 'weaver generate' command by
running the following.

    go get github.com/ServiceWeaver/weaver@latest
    go install github.com/ServiceWeaver/weaver/cmd/weaver@latest

Then, re-run 'weaver generate' and re-build your code. If the problem persists,
please file an issue at https://github.com/ServiceWeaver/weaver/issues.

`)

// Server stub implementations.

type main_server_stub struct {
	impl    weaver.Main
	addLoad func(key uint64, load float64)
}

// Check that main_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*main_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s main_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	default:
		return nil
	}
}

type subConfigureProvider_server_stub struct {
	impl    subConfigureProvider
	addLoad func(key uint64, load float64)
}

// Check that subConfigureProvider_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*subConfigureProvider_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s subConfigureProvider_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "GetResponseOption":
		return s.getResponseOption
	case "GetSubAuthParamName":
		return s.getSubAuthParamName
	case "GetSubFilePaths":
		return s.getSubFilePaths
	case "GetSubPublishPath":
		return s.getSubPublishPath
	case "GetUrlSubs":
		return s.getUrlSubs
	default:
		return nil
	}
}

func (s subConfigureProvider_server_stub) getResponseOption(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetResponseOption(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_ptr_responseOption_4a459b91(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s subConfigureProvider_server_stub) getSubAuthParamName(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetSubAuthParamName(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s subConfigureProvider_server_stub) getSubFilePaths(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetSubFilePaths(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_string_4af10117(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s subConfigureProvider_server_stub) getSubPublishPath(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.GetSubPublishPath(ctx)

	// Encode the results.
	enc := codegen.NewEncoder()
	enc.String(r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

func (s subConfigureProvider_server_stub) getUrlSubs(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 string
	a0 = dec.String()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, r1, appErr := s.impl.GetUrlSubs(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_string_4af10117(enc, r0)
	enc.Int(r1)
	enc.Error(appErr)
	return enc.Data(), nil
}

type subFileSourceProvider_server_stub struct {
	impl    subFileSourceProvider
	addLoad func(key uint64, load float64)
}

// Check that subFileSourceProvider_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*subFileSourceProvider_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s subFileSourceProvider_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "UpdateFileSub":
		return s.updateFileSub
	default:
		return nil
	}
}

func (s subFileSourceProvider_server_stub) updateFileSub(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 []string
	a0 = serviceweaver_dec_slice_string_4af10117(dec)

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateFileSub(ctx, a0)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_byte_87461245(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

type subURLSourceProvider_server_stub struct {
	impl    subURLSourceProvider
	addLoad func(key uint64, load float64)
}

// Check that subURLSourceProvider_server_stub implements the codegen.Server interface.
var _ codegen.Server = (*subURLSourceProvider_server_stub)(nil)

// GetStubFn implements the codegen.Server interface.
func (s subURLSourceProvider_server_stub) GetStubFn(method string) func(ctx context.Context, args []byte) ([]byte, error) {
	switch method {
	case "UpdateUrlSub":
		return s.updateUrlSub
	default:
		return nil
	}
}

func (s subURLSourceProvider_server_stub) updateUrlSub(ctx context.Context, args []byte) (res []byte, err error) {
	// Catch and return any panics detected during encoding/decoding/rpc.
	defer func() {
		if err == nil {
			err = codegen.CatchPanics(recover())
		}
	}()

	// Decode arguments.
	dec := codegen.NewDecoder(args)
	var a0 []string
	a0 = serviceweaver_dec_slice_string_4af10117(dec)
	var a1 int
	a1 = dec.Int()

	// TODO(rgrandl): The deferred function above will recover from panics in the
	// user code: fix this.
	// Call the local method.
	r0, appErr := s.impl.UpdateUrlSub(ctx, a0, a1)

	// Encode the results.
	enc := codegen.NewEncoder()
	serviceweaver_enc_slice_byte_87461245(enc, r0)
	enc.Error(appErr)
	return enc.Data(), nil
}

// Reflect stub implementations.

type main_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that main_reflect_stub implements the weaver.Main interface.
var _ weaver.Main = (*main_reflect_stub)(nil)

type subConfigureProvider_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that subConfigureProvider_reflect_stub implements the subConfigureProvider interface.
var _ subConfigureProvider = (*subConfigureProvider_reflect_stub)(nil)

func (s subConfigureProvider_reflect_stub) GetResponseOption(ctx context.Context) (r0 *responseOption, err error) {
	err = s.caller("GetResponseOption", ctx, []any{}, []any{&r0})
	return
}

func (s subConfigureProvider_reflect_stub) GetSubAuthParamName(ctx context.Context) (r0 string, err error) {
	err = s.caller("GetSubAuthParamName", ctx, []any{}, []any{&r0})
	return
}

func (s subConfigureProvider_reflect_stub) GetSubFilePaths(ctx context.Context, a0 string) (r0 []string, err error) {
	err = s.caller("GetSubFilePaths", ctx, []any{a0}, []any{&r0})
	return
}

func (s subConfigureProvider_reflect_stub) GetSubPublishPath(ctx context.Context) (r0 string, err error) {
	err = s.caller("GetSubPublishPath", ctx, []any{}, []any{&r0})
	return
}

func (s subConfigureProvider_reflect_stub) GetUrlSubs(ctx context.Context, a0 string) (r0 []string, r1 int, err error) {
	err = s.caller("GetUrlSubs", ctx, []any{a0}, []any{&r0, &r1})
	return
}

type subFileSourceProvider_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that subFileSourceProvider_reflect_stub implements the subFileSourceProvider interface.
var _ subFileSourceProvider = (*subFileSourceProvider_reflect_stub)(nil)

func (s subFileSourceProvider_reflect_stub) UpdateFileSub(ctx context.Context, a0 []string) (r0 []byte, err error) {
	err = s.caller("UpdateFileSub", ctx, []any{a0}, []any{&r0})
	return
}

type subURLSourceProvider_reflect_stub struct {
	caller func(string, context.Context, []any, []any) error
}

// Check that subURLSourceProvider_reflect_stub implements the subURLSourceProvider interface.
var _ subURLSourceProvider = (*subURLSourceProvider_reflect_stub)(nil)

func (s subURLSourceProvider_reflect_stub) UpdateUrlSub(ctx context.Context, a0 []string, a1 int) (r0 []byte, err error) {
	err = s.caller("UpdateUrlSub", ctx, []any{a0, a1}, []any{&r0})
	return
}

// AutoMarshal implementations.

var _ codegen.AutoMarshal = (*responseOption)(nil)

type __is_responseOption[T ~struct {
	weaver.AutoMarshal
	UpdateIntervalHours int    "toml:\"update_interval_hours,omitempty\""
	ProfileWebPage      string "toml:\"profile_web_page,omitempty\""
}] struct{}

var _ __is_responseOption[responseOption]

func (x *responseOption) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("responseOption.WeaverMarshal: nil receiver"))
	}
	enc.Int(x.UpdateIntervalHours)
	enc.String(x.ProfileWebPage)
}

func (x *responseOption) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("responseOption.WeaverUnmarshal: nil receiver"))
	}
	x.UpdateIntervalHours = dec.Int()
	x.ProfileWebPage = dec.String()
}

var _ codegen.AutoMarshal = (*subConfig)(nil)

type __is_subConfig[T ~struct {
	weaver.AutoMarshal
	PublicSubFilePaths        []string        "toml:\"public_sub_file_paths\""
	PrivateSubFilePaths       []string        "toml:\"private_sub_file_paths\""
	UrlSubFetchTimeoutSeconds int             "toml:\"url_sub_fetch_timeout_seconds\""
	PublicUrlSubs             []string        "toml:\"public_url_subs\""
	PrivateUrlSubs            []string        "toml:\"private_url_subs\""
	PrivateSubToken           string          "toml:\"private_sub_token\""
	SubPublishPath            string          "toml:\"sub_publish_path,omitempty\""
	SubAuthParamName          string          "toml:\"sub_auth_param_name\""
	ResponseOption            *responseOption "toml:\"response_option,omitempty\""
}] struct{}

var _ __is_subConfig[subConfig]

func (x *subConfig) WeaverMarshal(enc *codegen.Encoder) {
	if x == nil {
		panic(fmt.Errorf("subConfig.WeaverMarshal: nil receiver"))
	}
	serviceweaver_enc_slice_string_4af10117(enc, x.PublicSubFilePaths)
	serviceweaver_enc_slice_string_4af10117(enc, x.PrivateSubFilePaths)
	enc.Int(x.UrlSubFetchTimeoutSeconds)
	serviceweaver_enc_slice_string_4af10117(enc, x.PublicUrlSubs)
	serviceweaver_enc_slice_string_4af10117(enc, x.PrivateUrlSubs)
	enc.String(x.PrivateSubToken)
	enc.String(x.SubPublishPath)
	enc.String(x.SubAuthParamName)
	serviceweaver_enc_ptr_responseOption_4a459b91(enc, x.ResponseOption)
}

func (x *subConfig) WeaverUnmarshal(dec *codegen.Decoder) {
	if x == nil {
		panic(fmt.Errorf("subConfig.WeaverUnmarshal: nil receiver"))
	}
	x.PublicSubFilePaths = serviceweaver_dec_slice_string_4af10117(dec)
	x.PrivateSubFilePaths = serviceweaver_dec_slice_string_4af10117(dec)
	x.UrlSubFetchTimeoutSeconds = dec.Int()
	x.PublicUrlSubs = serviceweaver_dec_slice_string_4af10117(dec)
	x.PrivateUrlSubs = serviceweaver_dec_slice_string_4af10117(dec)
	x.PrivateSubToken = dec.String()
	x.SubPublishPath = dec.String()
	x.SubAuthParamName = dec.String()
	x.ResponseOption = serviceweaver_dec_ptr_responseOption_4a459b91(dec)
}

func serviceweaver_enc_slice_string_4af10117(enc *codegen.Encoder, arg []string) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.String(arg[i])
	}
}

func serviceweaver_dec_slice_string_4af10117(dec *codegen.Decoder) []string {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]string, n)
	for i := 0; i < n; i++ {
		res[i] = dec.String()
	}
	return res
}

func serviceweaver_enc_ptr_responseOption_4a459b91(enc *codegen.Encoder, arg *responseOption) {
	if arg == nil {
		enc.Bool(false)
	} else {
		enc.Bool(true)
		(*arg).WeaverMarshal(enc)
	}
}

func serviceweaver_dec_ptr_responseOption_4a459b91(dec *codegen.Decoder) *responseOption {
	if !dec.Bool() {
		return nil
	}
	var res responseOption
	(&res).WeaverUnmarshal(dec)
	return &res
}

// Encoding/decoding implementations.

func serviceweaver_enc_slice_byte_87461245(enc *codegen.Encoder, arg []byte) {
	if arg == nil {
		enc.Len(-1)
		return
	}
	enc.Len(len(arg))
	for i := 0; i < len(arg); i++ {
		enc.Byte(arg[i])
	}
}

func serviceweaver_dec_slice_byte_87461245(dec *codegen.Decoder) []byte {
	n := dec.Len()
	if n == -1 {
		return nil
	}
	res := make([]byte, n)
	for i := 0; i < n; i++ {
		res[i] = dec.Byte()
	}
	return res
}
