// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"raycat/internal/ent/predicate"
	"raycat/internal/ent/subscribe"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SubscribeUpdate is the builder for updating Subscribe entities.
type SubscribeUpdate struct {
	config
	hooks    []Hook
	mutation *SubscribeMutation
}

// Where appends a list predicates to the SubscribeUpdate builder.
func (su *SubscribeUpdate) Where(ps ...predicate.Subscribe) *SubscribeUpdate {
	su.mutation.Where(ps...)
	return su
}

// SetKind sets the "kind" field.
func (su *SubscribeUpdate) SetKind(s subscribe.Kind) *SubscribeUpdate {
	su.mutation.SetKind(s)
	return su
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableKind(s *subscribe.Kind) *SubscribeUpdate {
	if s != nil {
		su.SetKind(*s)
	}
	return su
}

// SetLocation sets the "location" field.
func (su *SubscribeUpdate) SetLocation(s string) *SubscribeUpdate {
	su.mutation.SetLocation(s)
	return su
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableLocation(s *string) *SubscribeUpdate {
	if s != nil {
		su.SetLocation(*s)
	}
	return su
}

// SetUpdateTimeoutSeconds sets the "update_timeout_seconds" field.
func (su *SubscribeUpdate) SetUpdateTimeoutSeconds(i int) *SubscribeUpdate {
	su.mutation.ResetUpdateTimeoutSeconds()
	su.mutation.SetUpdateTimeoutSeconds(i)
	return su
}

// SetNillableUpdateTimeoutSeconds sets the "update_timeout_seconds" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableUpdateTimeoutSeconds(i *int) *SubscribeUpdate {
	if i != nil {
		su.SetUpdateTimeoutSeconds(*i)
	}
	return su
}

// AddUpdateTimeoutSeconds adds i to the "update_timeout_seconds" field.
func (su *SubscribeUpdate) AddUpdateTimeoutSeconds(i int) *SubscribeUpdate {
	su.mutation.AddUpdateTimeoutSeconds(i)
	return su
}

// SetLatency sets the "latency" field.
func (su *SubscribeUpdate) SetLatency(i int64) *SubscribeUpdate {
	su.mutation.ResetLatency()
	su.mutation.SetLatency(i)
	return su
}

// SetNillableLatency sets the "latency" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableLatency(i *int64) *SubscribeUpdate {
	if i != nil {
		su.SetLatency(*i)
	}
	return su
}

// AddLatency adds i to the "latency" field.
func (su *SubscribeUpdate) AddLatency(i int64) *SubscribeUpdate {
	su.mutation.AddLatency(i)
	return su
}

// SetExpireAt sets the "expire_at" field.
func (su *SubscribeUpdate) SetExpireAt(t time.Time) *SubscribeUpdate {
	su.mutation.SetExpireAt(t)
	return su
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableExpireAt(t *time.Time) *SubscribeUpdate {
	if t != nil {
		su.SetExpireAt(*t)
	}
	return su
}

// SetCreatedAt sets the "created_at" field.
func (su *SubscribeUpdate) SetCreatedAt(t time.Time) *SubscribeUpdate {
	su.mutation.SetCreatedAt(t)
	return su
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (su *SubscribeUpdate) SetNillableCreatedAt(t *time.Time) *SubscribeUpdate {
	if t != nil {
		su.SetCreatedAt(*t)
	}
	return su
}

// Mutation returns the SubscribeMutation object of the builder.
func (su *SubscribeUpdate) Mutation() *SubscribeMutation {
	return su.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (su *SubscribeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, su.sqlSave, su.mutation, su.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (su *SubscribeUpdate) SaveX(ctx context.Context) int {
	affected, err := su.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (su *SubscribeUpdate) Exec(ctx context.Context) error {
	_, err := su.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (su *SubscribeUpdate) ExecX(ctx context.Context) {
	if err := su.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (su *SubscribeUpdate) check() error {
	if v, ok := su.mutation.Kind(); ok {
		if err := subscribe.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Subscribe.kind": %w`, err)}
		}
	}
	return nil
}

func (su *SubscribeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := su.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscribe.Table, subscribe.Columns, sqlgraph.NewFieldSpec(subscribe.FieldID, field.TypeUUID))
	if ps := su.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := su.mutation.Kind(); ok {
		_spec.SetField(subscribe.FieldKind, field.TypeEnum, value)
	}
	if value, ok := su.mutation.Location(); ok {
		_spec.SetField(subscribe.FieldLocation, field.TypeString, value)
	}
	if value, ok := su.mutation.UpdateTimeoutSeconds(); ok {
		_spec.SetField(subscribe.FieldUpdateTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := su.mutation.AddedUpdateTimeoutSeconds(); ok {
		_spec.AddField(subscribe.FieldUpdateTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := su.mutation.Latency(); ok {
		_spec.SetField(subscribe.FieldLatency, field.TypeInt64, value)
	}
	if value, ok := su.mutation.AddedLatency(); ok {
		_spec.AddField(subscribe.FieldLatency, field.TypeInt64, value)
	}
	if value, ok := su.mutation.ExpireAt(); ok {
		_spec.SetField(subscribe.FieldExpireAt, field.TypeTime, value)
	}
	if value, ok := su.mutation.CreatedAt(); ok {
		_spec.SetField(subscribe.FieldCreatedAt, field.TypeTime, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, su.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscribe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	su.mutation.done = true
	return n, nil
}

// SubscribeUpdateOne is the builder for updating a single Subscribe entity.
type SubscribeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscribeMutation
}

// SetKind sets the "kind" field.
func (suo *SubscribeUpdateOne) SetKind(s subscribe.Kind) *SubscribeUpdateOne {
	suo.mutation.SetKind(s)
	return suo
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableKind(s *subscribe.Kind) *SubscribeUpdateOne {
	if s != nil {
		suo.SetKind(*s)
	}
	return suo
}

// SetLocation sets the "location" field.
func (suo *SubscribeUpdateOne) SetLocation(s string) *SubscribeUpdateOne {
	suo.mutation.SetLocation(s)
	return suo
}

// SetNillableLocation sets the "location" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableLocation(s *string) *SubscribeUpdateOne {
	if s != nil {
		suo.SetLocation(*s)
	}
	return suo
}

// SetUpdateTimeoutSeconds sets the "update_timeout_seconds" field.
func (suo *SubscribeUpdateOne) SetUpdateTimeoutSeconds(i int) *SubscribeUpdateOne {
	suo.mutation.ResetUpdateTimeoutSeconds()
	suo.mutation.SetUpdateTimeoutSeconds(i)
	return suo
}

// SetNillableUpdateTimeoutSeconds sets the "update_timeout_seconds" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableUpdateTimeoutSeconds(i *int) *SubscribeUpdateOne {
	if i != nil {
		suo.SetUpdateTimeoutSeconds(*i)
	}
	return suo
}

// AddUpdateTimeoutSeconds adds i to the "update_timeout_seconds" field.
func (suo *SubscribeUpdateOne) AddUpdateTimeoutSeconds(i int) *SubscribeUpdateOne {
	suo.mutation.AddUpdateTimeoutSeconds(i)
	return suo
}

// SetLatency sets the "latency" field.
func (suo *SubscribeUpdateOne) SetLatency(i int64) *SubscribeUpdateOne {
	suo.mutation.ResetLatency()
	suo.mutation.SetLatency(i)
	return suo
}

// SetNillableLatency sets the "latency" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableLatency(i *int64) *SubscribeUpdateOne {
	if i != nil {
		suo.SetLatency(*i)
	}
	return suo
}

// AddLatency adds i to the "latency" field.
func (suo *SubscribeUpdateOne) AddLatency(i int64) *SubscribeUpdateOne {
	suo.mutation.AddLatency(i)
	return suo
}

// SetExpireAt sets the "expire_at" field.
func (suo *SubscribeUpdateOne) SetExpireAt(t time.Time) *SubscribeUpdateOne {
	suo.mutation.SetExpireAt(t)
	return suo
}

// SetNillableExpireAt sets the "expire_at" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableExpireAt(t *time.Time) *SubscribeUpdateOne {
	if t != nil {
		suo.SetExpireAt(*t)
	}
	return suo
}

// SetCreatedAt sets the "created_at" field.
func (suo *SubscribeUpdateOne) SetCreatedAt(t time.Time) *SubscribeUpdateOne {
	suo.mutation.SetCreatedAt(t)
	return suo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (suo *SubscribeUpdateOne) SetNillableCreatedAt(t *time.Time) *SubscribeUpdateOne {
	if t != nil {
		suo.SetCreatedAt(*t)
	}
	return suo
}

// Mutation returns the SubscribeMutation object of the builder.
func (suo *SubscribeUpdateOne) Mutation() *SubscribeMutation {
	return suo.mutation
}

// Where appends a list predicates to the SubscribeUpdate builder.
func (suo *SubscribeUpdateOne) Where(ps ...predicate.Subscribe) *SubscribeUpdateOne {
	suo.mutation.Where(ps...)
	return suo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (suo *SubscribeUpdateOne) Select(field string, fields ...string) *SubscribeUpdateOne {
	suo.fields = append([]string{field}, fields...)
	return suo
}

// Save executes the query and returns the updated Subscribe entity.
func (suo *SubscribeUpdateOne) Save(ctx context.Context) (*Subscribe, error) {
	return withHooks(ctx, suo.sqlSave, suo.mutation, suo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (suo *SubscribeUpdateOne) SaveX(ctx context.Context) *Subscribe {
	node, err := suo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (suo *SubscribeUpdateOne) Exec(ctx context.Context) error {
	_, err := suo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (suo *SubscribeUpdateOne) ExecX(ctx context.Context) {
	if err := suo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (suo *SubscribeUpdateOne) check() error {
	if v, ok := suo.mutation.Kind(); ok {
		if err := subscribe.KindValidator(v); err != nil {
			return &ValidationError{Name: "kind", err: fmt.Errorf(`ent: validator failed for field "Subscribe.kind": %w`, err)}
		}
	}
	return nil
}

func (suo *SubscribeUpdateOne) sqlSave(ctx context.Context) (_node *Subscribe, err error) {
	if err := suo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(subscribe.Table, subscribe.Columns, sqlgraph.NewFieldSpec(subscribe.FieldID, field.TypeUUID))
	id, ok := suo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscribe.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := suo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscribe.FieldID)
		for _, f := range fields {
			if !subscribe.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscribe.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := suo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := suo.mutation.Kind(); ok {
		_spec.SetField(subscribe.FieldKind, field.TypeEnum, value)
	}
	if value, ok := suo.mutation.Location(); ok {
		_spec.SetField(subscribe.FieldLocation, field.TypeString, value)
	}
	if value, ok := suo.mutation.UpdateTimeoutSeconds(); ok {
		_spec.SetField(subscribe.FieldUpdateTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := suo.mutation.AddedUpdateTimeoutSeconds(); ok {
		_spec.AddField(subscribe.FieldUpdateTimeoutSeconds, field.TypeInt, value)
	}
	if value, ok := suo.mutation.Latency(); ok {
		_spec.SetField(subscribe.FieldLatency, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.AddedLatency(); ok {
		_spec.AddField(subscribe.FieldLatency, field.TypeInt64, value)
	}
	if value, ok := suo.mutation.ExpireAt(); ok {
		_spec.SetField(subscribe.FieldExpireAt, field.TypeTime, value)
	}
	if value, ok := suo.mutation.CreatedAt(); ok {
		_spec.SetField(subscribe.FieldCreatedAt, field.TypeTime, value)
	}
	_node = &Subscribe{config: suo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, suo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscribe.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	suo.mutation.done = true
	return _node, nil
}
