// Code generated by ent, DO NOT EDIT.

package subscribe

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the subscribe type in the database.
	Label = "subscribe"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldKind holds the string denoting the kind field in the database.
	FieldKind = "kind"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldUpdateTimeoutSeconds holds the string denoting the update_timeout_seconds field in the database.
	FieldUpdateTimeoutSeconds = "update_timeout_seconds"
	// FieldLatency holds the string denoting the latency field in the database.
	FieldLatency = "latency"
	// FieldExpireAt holds the string denoting the expire_at field in the database.
	FieldExpireAt = "expire_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the subscribe in the database.
	Table = "subscribes"
)

// Columns holds all SQL columns for subscribe fields.
var Columns = []string{
	FieldID,
	FieldKind,
	FieldLocation,
	FieldUpdateTimeoutSeconds,
	FieldLatency,
	FieldExpireAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUpdateTimeoutSeconds holds the default value on creation for the "update_timeout_seconds" field.
	DefaultUpdateTimeoutSeconds int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Kind defines the type for the "kind" enum field.
type Kind string

// KindNone is the default value of the Kind enum.
const DefaultKind = KindNone

// Kind values.
const (
	KindURLSub   Kind = "url_sub"
	KindLocalSub Kind = "local_sub"
	KindTplSub   Kind = "tpl_sub"
	KindSubEntry Kind = "sub_entry"
	KindNone     Kind = "none"
)

func (k Kind) String() string {
	return string(k)
}

// KindValidator is a validator for the "kind" field enum values. It is called by the builders before save.
func KindValidator(k Kind) error {
	switch k {
	case KindURLSub, KindLocalSub, KindTplSub, KindSubEntry, KindNone:
		return nil
	default:
		return fmt.Errorf("subscribe: invalid enum value for kind field: %q", k)
	}
}

// OrderOption defines the ordering options for the Subscribe queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByKind orders the results by the kind field.
func ByKind(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKind, opts...).ToFunc()
}

// ByLocation orders the results by the location field.
func ByLocation(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLocation, opts...).ToFunc()
}

// ByUpdateTimeoutSeconds orders the results by the update_timeout_seconds field.
func ByUpdateTimeoutSeconds(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdateTimeoutSeconds, opts...).ToFunc()
}

// ByLatency orders the results by the latency field.
func ByLatency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatency, opts...).ToFunc()
}

// ByExpireAt orders the results by the expire_at field.
func ByExpireAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpireAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
